# Generated by Django 4.1.4 on 2022-12-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the project', max_length=20)),
                ('url', models.URLField(help_text="The URL for the project's repo or blog post")),
                ('tech', models.CharField(help_text='Comma separated list of technologies used by the project', max_length=200)),
                ('synopsis', models.TextField(help_text='Summary of the project')),
            ],
        ),
    ]
