# Generated by Django 4.1.4 on 2022-12-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, help_text="The URL for the project's repo or blog post"),
        ),
    ]
