# Generated by Django 4.1.4 on 2023-01-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230108_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='article',
            field=models.TextField(blank=True, help_text='Full article on the project, in markdown'),
        ),
    ]
