name: Static web page CI

on:
    push:
        branches:
        - unchained
        paths:
        - infra/web

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Terraform
    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6
        terraform_wrapper: false

    - name: Terraform Init
      id: init
      env:
        ARM_CLIENT_ID: {{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: {{ secrets.ARM_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: {{ secrets.ARM_CLIENT_ID }}
        ARM_TENANT_ID: {{ secrets.ARM_CLIENT_ID }}
      working-directory: infra/web
      shell: bash

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -input=false -no-color -out tf.plan
      env:
        ARM_CLIENT_ID: {{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: {{ secrets.ARM_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: {{ secrets.ARM_CLIENT_ID }}
        ARM_TENANT_ID: {{ secrets.ARM_CLIENT_ID }}
      working-directory: infra/web
      shell: bash

    - name: Terraform Show
      id: show
      run: terraform show -no-color tf.plan
      working-directory: infra/web
      env:
        ARM_CLIENT_ID: {{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: {{ secrets.ARM_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: {{ secrets.ARM_CLIENT_ID }}
        ARM_TENANT_ID: {{ secrets.ARM_CLIENT_ID }}
      shell: bash
