name: Static web page CI

on:
    push:
        branches: [ main ]
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_SECRET }}
          
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name cmeadowstech --auth-mode key -d '$web' -s .
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "cmeadowstech-cdn" --name "https://cmeadowstech.azureedge.net" --resource-group "website"
           
  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
